# workflow definition

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world- # name of this workflow 
spec:
  entrypoint: whalesay  # define whalesay as main template
  templates:
    - name: whalesay  # define whalesay template
      container:
        image: docker/whalesay
        command: [ cowsay ]
        args: [ "Hello world" ] # this tempalte runs cowsay in the whalesay image with arguments "hellow world" 